# Use the latest Ubuntu image as the base
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

RUN pip install cryptography

# Copy all files from the current directory to the container's /app directory
COPY . /app

# Define the command to run the Python file named sparrow.py
EXPOSE 8000
CMD ["python3", "sparrow.py", "0.0.0.0", "8000"]
