version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  webserver:
    build:
      context: ../../code
      dockerfile: Dockerfile

volumes:
  caddy_data:
  caddy_config:
