---

- name: PreReqs | APT
  ansible.builtin.apt:
    - name: "{{item}}"
    - state: present
  with_items:
    - python3
    - pip3


- name: PreReqs | pip3
  ansible.buildin.pip:
    - name: "{{item}}"
    - state: present
  with_items:
    - cryptography
    - datetime
    - enum
    - json
    - os
    - socket
    - ssl
    - sys